name: Maven Build and Auto PR

on:
  push:
    branches:
      - "development"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_MVN }}
          ACTOR: ${{ secrets.MVN_ACTOR }}
        run: |
          echo "<settings><servers><server><id>github</id><username>${ACTOR}</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
          mvn -B package --file pom.xml

  pull-request:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Auto Pull Request
        uses: diillson/auto-pull-request@v1.0.1
        with:
          source_branch: ""
          destination_branch: "main"
          pr_title: "Pulling ${{ github.ref }} into main"
          pr_body: |
            :crown: *An automated PR*
            _Created by [diillson/auto-pull-request](https://github.com/diillson/auto-pull-request)_
          pr_template: ".github/PULL_REQUEST_TEMPLATE.md"
          pr_assignee: ${{ github.actor }}
          pr_label: "auto-pr"
          pr_draft: false
          pr_allow_empty: true
          github_token: ${{ secrets.CUSTOM_TOKEN }}